name: NASA-PROJECT
on: workflow_dispatch
jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          npm install
          npm run install-server
          npm run install-client
      - name: Deploy app
        run: npm run deploy
